name: dolirest
description: "A Dolibarr Rest API client."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  double_back_to_close: ^2.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  open_filex: ^4.4.0
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5
  hive: ^2.2.3
  path_provider: ^2.1.0
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2

  dropdown_search: ^5.0.6
  flutter_native_splash: ^2.3.10
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  dependency_validator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/smbi.png

