name: dolirest
description: "A Dolibarr Rest API client."
publish_to: 'none'
version: 0.1.7

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  double_back_to_close: ^2.0.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.2
  open_filex: ^4.4.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.5
  path_provider: ^2.1.4
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.2
  dropdown_search: ^6.0.0
  flutter_spinkit: ^5.2.0
  flutter_initicon: ^3.0.1
  fpdart: ^1.1.0
  data_table_2: ^2.5.15
  dio: ^5.7.0
  flex_color_scheme: ^8.0.0
  restart_app: ^1.3.2
  hive_ce: ^2.7.0+1
  hive_ce_flutter: ^2.1.0
  pretty_dio_logger: ^1.4.0
  

dev_dependencies:
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  dependency_validator: ^5.0.2
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  hive_ce_generator: ^1.7.0



flutter:
  uses-material-design: true
  assets:
    - assets/images/

