name: dolirest
description: "A Dolibarr Rest API client."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  double_back_to_close: ^2.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  form_builder_extra_fields: ^10.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.18.1
  lottie: ^3.1.0
  open_filex: ^4.4.0
  permission_handler: ^11.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/smbi.png
    - assets/images/splashscreen.gif

